### ISSUE TITLE
Tags/ Categories are duplicated in header

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/wp2grav_exporter#10]
Sample export:
```
taxonomy:
    category:
        - a
        - a
    tag:
        - in
        - in
```
