### ISSUE TITLE
Role wp_authenticated_user is mis-named

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/wp2grav_exporter#12]
```
wp_authenticated_user:
    icon: cog
    readableName: Subscriber
    description: 'Grant WordPress roles login rights to admin portal'
    access:
        admin:
            login: true
```

`readableName` should be "Authenticated User", but it's using the last role in the for loop.
